AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template OpsWorks: Launches OpsWorks stack,
  layer, instances and associated resources to run a PHP application. ** This template
  creates one or more Amazon EC2 instances. You will be billed for the AWS resources
  used if you create a stack from this template.'
Mappings:
  Region2Principal:
    ap-northeast-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    ap-southeast-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    ap-southeast-2:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    cn-north-1:
      EC2Principal: ec2.amazonaws.com.cn
      OpsWorksPrincipal: opsworks.amazonaws.com.cn
    eu-central-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    eu-west-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    sa-east-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    us-east-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    us-west-1:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
    us-west-2:
      EC2Principal: ec2.amazonaws.com
      OpsWorksPrincipal: opsworks.amazonaws.com
Outputs:
  AppId:
    Description: Application Id for the newly created OpsWorks application
    Value:
      Ref: MyApp
  StackId:
    Description: Stack Id for the newly created OpsWorks stack
    Value:
      Ref: MyStack
Resources:
  MyApp:
    Properties:
      AppSource:
        Revision: version1
        Type: git
        Url: git://github.com/amazonwebservices/opsworks-demo-php-simple-app.git
      Attributes:
        DocumentRoot: ' '
      Name: MyPHPApp
      StackId:
        Ref: MyStack
      Type: php
    Type: AWS::OpsWorks::App
  MyInstance:
    Properties:
      InstanceType: m1.small
      LayerIds:
      - Ref: MyLayer
      RootDeviceType: ebs
      StackId:
        Ref: MyStack
    Type: AWS::OpsWorks::Instance
  MyLayer:
    DependsOn: MyApp
    Properties:
      AutoAssignElasticIps: 'false'
      AutoAssignPublicIps: 'true'
      EnableAutoHealing: 'true'
      Name: MyPHPApp
      Shortname: php-app
      StackId:
        Ref: MyStack
      Type: php-app
    Type: AWS::OpsWorks::Layer
  MyStack:
    Properties:
      DefaultInstanceProfileArn:
        Fn::GetAtt:
        - OpsWorksInstanceProfile
        - Arn
      Name:
        Ref: AWS::StackName
      ServiceRoleArn:
        Fn::GetAtt:
        - OpsWorksServiceRole
        - Arn
    Type: AWS::OpsWorks::Stack
  OpsWorksInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: OpsWorksInstanceRole
    Type: AWS::IAM::InstanceProfile
  OpsWorksInstanceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::FindInMap:
              - Region2Principal
              - Ref: AWS::Region
              - EC2Principal
      Path: /
    Type: AWS::IAM::Role
  OpsWorksServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::FindInMap:
              - Region2Principal
              - Ref: AWS::Region
              - OpsWorksPrincipal
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ec2:*
            - iam:PassRole
            - cloudwatch:GetMetricStatistics
            - elasticloadbalancing:*
            Effect: Allow
            Resource: '*'
        PolicyName: opsworks-service
    Type: AWS::IAM::Role

